# my makefile
# newbie stuff :)

CC=gcc

# -g if for debugging 
# -c for stopping at compile (no assembly)
CFLAGS= -g
BIN=myprogram
SRC=main.c

$BIN: $SRC
  $CC $CFLAGS $SRC
  
# this is routine for makefile (cleanup)
# remove all object files (generated by comiler) and executable.
clean: 
  rm *.o $BIN
